name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]


jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install dependencies 
        run: npm ci 

      - name: Check style        
        run: npm run eslint

      - name: Run npm test
        run: npm run test

      - name: Run npm run build
        run: npm run build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      
      - name: try to fail 
        run: exit 1

      - name: Deploy
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip')
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"     
      
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    if: ${{ contains( join( github.event.commits.*.message, ', '), '#skip' ) == false }}
    steps:
     - name: Checkout repository
       uses: actions/checkout@v4
       with:
          fetch-depth: 0
     - name: Bump version and push tag
       uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
       env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify: 
      needs: [simple_deployment_pipeline]
      runs-on: ubuntu-latest
      if: always()
      steps:
      - name: err_msg 
        uses: sarisia/actions-status-discord@v1
        if: ${{ needs.simple_deployment_pipeline.result == 'failure' || needs.simple_deployment_pipeline == 'cancelled' }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          nodetail: true
          username: Fullstack part 11 Hook
          content: " :x: Build failed! The pipeline encountered an error"
          title: "Failure details"
          description: |
            **Repo**: `${{ github.repository }}`
            **Branch**: `${{ github.ref_name }}`
            **Commit**: `${{ github.sha }}`
            **Message**: `${{ github.event.commits[0].message }}`
            **Author**: `${{ github.event.commits[0].author.name }}`
            **Workflow**: `${{ github.workflow }}`
            **Job**: `${{ github.job }}`

            [View Commit](${{ github.event.commits[0].url }})
            [View Workflow Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id}})

          image: ${{ secrets.EMBED_IMAGE }}
          color: 0xff0000
      - name: success_msg
        uses: sarisia/actions-status-discord@v1
        if: ${{ needs.simple_deployment_pipeline.result == 'success' }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          nodetail: true
          username: Fullstack part 11 Hook
          color: 0x00ff00
          content: ":white_check_mark:  Deployement Successful! A new version deployed to production"
          title: "Deployement Details"
          description: | 
            **Commit**: `${{ github.sha }}`
            **Message**: `${{ github.event.commits[0].message }}`
            **Author**: `${{ github.event.commits[0].author.name }}`

          url: "https://github.com/sarisia/actions-status-discord"
          avatar_url: ${{ secrets.AVATAR_URL }}